markdown: kramdown
pygments: true
permalink: /:year/:month/:title.html

name: "wangxian.me"

author: "wangxian"
atom-baseurl: "http://wangxian.me"
disqus: "xian366"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: MyLinks
    class: fa fa-link
    href: /links.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Lofter
    class: fa fa-film
    href: http://xian366.lofter.com/
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

