markdown: kramdown
highlighter: pygments

permalink: /:year/:month/:title.html
name: "wangxian.me"

author: "wangxian"
atom-baseurl: "http://wangxian.me"
disqus: "xian366"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: Links
    class: fa fa-link
    href: /links.html
  - title: "Site Search"
    class: fa fa-search
    href: /search.html
  - title: "My Lofter"
    class: fa fa-film
    href: http://xian366.lofter.com/
  - title: "About Me"
    class: fa fa-user
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

